# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
dist: precise
group: edge
env:
  global:
    - NOT_CRAN = true
before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi
#  echo "options(repos = c(CRAN='https://cran.rstudio.com'))" > ~/.Rprofile
#  - sudo apt-get autoclean
#  - sudo aptitude install libgdal-dev
apt_packages:
  - libnetcdf-dev
  - udunits-bin
  - libudunits2-dev
  - netcdf-bin
#  - libproj-dev
#  - libcurl4-gnutls-dev
#  - libdap-dev
#  - libgdal-dev
#  - libgdal1h
#  - libhdf5-7=1.8.11-3ubuntu1~precise1~ppa1
#  - libhdf5-dev
#  - libhdf5-serial-dev
#  - libgdal-dev
  - libgdal1-dev
  - libgeos-dev
  - libproj0

#r_binary_packages:
#  - rgdal
#  - rgeos
#  - data.table
r_packages:
  - data.table