#' Analyze time series with different method.
#' @param TS A time series with first column the Date.
#' @param method A string showing the method used to calculate mean value, e.g., "annual".
#' more information please refer to details.
#' @param omitNA A boolean showing in the calculation, whether NA is omitted, default is TRUE.
#' @param output A character representing the output type, if you want to use \code{analyzeTS_comb}
#' to combine different output from this function, you can choose \code{output = 'ggplot'}, if not
#' assigned, normal data array will be returned.
#' @param ..., \code{title, x, y} showing the title and x and y axis of the plot, shoud be a string.
#' @details
#' There are following methods to be selected, 
#' "annual": annual rainfall of each year is plotted.  
#' "winter", "spring", "autumn", "summer": seasonal rainfall of each year is plotted.
#' Month(number 1 to 12): month rainfall of each year is plotted, e.g. march rainfall of each year.
#' 
#' Since "winter" is a crossing year, 12, 1, 2, 12 is in former year, and 1, 2 are in latter year.
#' so winter belongs to the latter year.
#' 
#' @return The annual/monthly/seasonal analysis of the input time series.
#' @examples
#' 
#' data(testdl)
#' TS  <- testdl[[1]]
#' 
#' # Get the mean spring precipitation.
#' a <- analyzeTS(TS, method = 'spring')
#' a <- analyzeTS(TS, method = 'spring', omitNA = FALSE)
#' 
#' 
#' a <- analyzeTS(TS, method = 'winter')
#' a
#' # Get special month precipitation, e.g. march.
#' a <- analyzeTS(TS, method = 3)
#' a
#' 
#' # We can also get annual precipitation.
#' a <- analyzeTS(TS, method = 'annual')
#' a
#'
#' @export
analyzeTS <- function (TS, method, omitNA = TRUE, output = 'data', ...) {
  Date <- as.POSIXlt(TS[, 1])
  year <- Date$year + 1900
  mon <- Date$mon + 1
  
  
  
  data <- getMeanPreci(TS[, 2], yearIndex = year, monthIndex = mon, 
                         method = method, omitNA = omitNA, plot = TRUE, fullResults = TRUE)
  
  if (output == 'ggplot') {
    data <- data.frame(Date = names(data), value = data, name = method)
    
  }
  
  return(data)
}
 



#' Combine rainfall analysis together, to generate multiplot.
#' @param ... different barplots generated by \code{analyzeTS(, output = 'ggplot')}, refer to details.
#' @details
#' ..., representing different ouput generated by \code{analyzeTS(, output = 'ggplot')}, they 
#' have to be of the same type, e.g., 
#' 1. Jan precipitation of different years, Feb precipitation of different years, and... 
#' They are both monthly precipitation, and they share x axis.
#' 
#' 2. Mean monthly precipitation of different dataset. e.g., long term mean monthly precipitation
#' and short term mean monthly precipitation. They are both mean monthly precipitation.
#' 
#' @param nrow A number showing the number of rows.
#' @param list If input is a list containing different ggplot data, use l\code{list = inputlist}.
#' NOTE: yOU HAVE TO PUT A \code{list = }, before your list.
#' @return A combined barplot of the analysis.
#' @examples
#' 
#' data(testdl)
#' TS  <- testdl[[1]]
#' 
#' #output type of analyzeTS() has to be 'ggplot'.
#' a <- analyzeTS(TS, method = 'spring', output = 'ggplot')
#' b <- analyzeTS(TS, method = 'summer', output = 'ggplot')
#' 
#' analyzeTS_comb(a, b)
#' 
#' 
#' 
#' a <- analyzeTS(TS, method = 3, output = 'ggplot')
#' b <- analyzeTS(TS, method = 4, output = 'ggplot')
#' analyzeTS_comb(a, b)
#' 
#' @export
#' @import ggplot2
analyzeTS_comb <- function (..., list = NULL, nrow = 1) {
  if (!is.null(list)) {
    data_ggplot <- do.call('rbind', list)
  } else {
    
    bars <- list(...)
    checkBind(bars, 'rbind')
    data_ggplot <- do.call('rbind', bars)
  }
  if (!class(data_ggplot) == 'data.frame') {
    warning('Your input is probably a list, but you forget to add "list = " before it.
            Try again, or check help for more information.')
  }
  
  data_ggplot$Date <- factor(data_ggplot$Date, levels = sort(unique(data_ggplot$Date)), ordered = TRUE)
  data_ggplot$name <- factor(data_ggplot$name, levels = data_ggplot$name, ordered = TRUE)
  
  theme_set(theme_bw())
  
  mainLayer <- with(data_ggplot, {
    ggplot(data_ggplot)+
      geom_bar(aes(x = Date, y = value),fill = 'cyan', stat = 'identity', colour = 'black', width = .6)+
      facet_wrap( ~ name, nrow = nrow) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
  })
  
  print (mainLayer)
  
} 
  
  
  
#' get L moment analysis of the input distribution
#' 
#' @param dis A distribution, for hydrology usually a time series with only data column without time.
#' @return The mean, L-variation, L-skewness and L-kurtosis of the input distribution
#' @examples
#' dis <- seq(1, 100)
#' getLMom(dis)
#' @export
#' @importFrom lmom samlmu
#' 
getLMom <- function(dis){
  
  LMom <- samlmu(dis, nmom = 4, ratios = TRUE)
  
  mean <- LMom[1]
  LCV <- LMom[2]/LMom[1]
  Lskew <- LMom[3]
  Lkur <- LMom[4]
  
  output <- data.frame(mean = mean, Lcv = LCV, Lskew = Lskew, Lkur = Lkur)
  return(output)
}

#' get moment analysis of the input distribution
#' 
#' @param dis A distribution, for hydrology usually a time series with only data column without time.
#' @return The mean, variation, skewness and kurtosis of the input distribution
#' @examples
#' dis <- seq(1, 100)
#' getMoment(dis)
#' @export
#' @importFrom moments skewness kurtosis
#' @importFrom stats var
getMoment <- function(dis) {
  mean <- mean(dis, na.rm = TRUE)
  variance <- var(dis, na.rm = TRUE)
  skewness <- skewness(dis, na.rm = TRUE)
  kurtosis <- kurtosis(dis, na.rm = TRUE)
  
  output <- data.frame(mean=mean, Variance = variance, Skewness = skewness, Kurtosis = kurtosis)
  
  return(output)
}
