
#' Extract common period or certain period from a list of different dataframes of time series.
#' 
#' @param datalist A list of different dataframes of time series .
#' @param startDate A Date showing the start of the extract period, default as NULL.
#' @param endDate A Date showing the end of the extract period, default as NULL.
#' @param commonPeriod A boolean showing whether the common period is extracted. If chosen, startDate and endDate
#' should be NULL.
#' @return A list with all the time series inside containing the same period.
# @examples
# str(datalist)
# List of 5
# $ AAA:'data.frame':  5602 obs. of  2 variables:
#  ..$ Date: Factor w/ 5602 levels "1999-10-28","1999-10-29",..: 1 2 3 4 5 6 7 8 9 10 ...
# ..$ AAA : num [1:5602] 0 0 0.4 0 0.2 46.6 1.8 0 0 31.2 ...
# $ BBB:'data.frame':	5977 obs. of  2 variables:
#   ..$ Date: Date[1:5977], format: "1999-01-01" "1999-01-02" "1999-01-03" ...
# ..$ BBB : num [1:5977] 0 1.4 0 0 0 0 0 19.7 42.9 4.7 ...
# $ CCC:'data.frame':	5977 obs. of  2 variables:
#   ..$ Date: Date[1:5977], format: "1999-01-01" "1999-01-02" "1999-01-03" ...
# ..$ CCC : num [1:5977] 0 0 0 0 0 0 0 11 28.6 6.2 ...
# $ DDD:'data.frame':	6307 obs. of  2 variables:
#   ..$ Date: Factor w/ 6307 levels "1998-01-01","1998-01-02",..: 1 2 3 4 5 6 7 8 9 10 ...
# ..$ DDD : num [1:6307] NA NA NA NA NA NA NA NA NA NA ...
# $ EEE:'data.frame':	5977 obs. of  2 variables:
#   ..$ Date: Date[1:5977], format: "1999-01-01" "1999-01-02" "1999-01-03" ...
# ..$ EEE : num [1:5977] 0 0 0 0 0 0 0 16.2 30 9 ...
# 
# datalist_new <- extractPeriod(datalist, commonPeriod = T)
# 
# str(datalist_new)
# 
# List of 5
# $ AAA:'data.frame':  5602 obs. of  2 variables:
#   ..$ Date: Date[1:5602], format: "1999-10-28" "1999-10-29" "1999-10-30" ...
# ..$ AAA : num [1:5602] 0 0 0.4 0 0.2 46.6 1.8 0 0 31.2 ...
# $ BBB:'data.frame':	5602 obs. of  2 variables:
#   ..$ Date: Date[1:5602], format: "1999-10-28" "1999-10-29" "1999-10-30" ...
# ..$ BBB : num [1:5602] 0 0 2.1 0 0.1 48 0 0 8.3 25.6 ...
# $ CCC:'data.frame':	5602 obs. of  2 variables:
#   ..$ Date: Date[1:5602], format: "1999-10-28" "1999-10-29" "1999-10-30" ...
# ..$ CCC : num [1:5602] 0 0 1.6 0 0 46.5 0 0 9.2 27.1 ...
# $ DDD:'data.frame':	5602 obs. of  2 variables:
#   ..$ Date: Date[1:5602], format: "1999-10-28" "1999-10-29" "1999-10-30" ...
# ..$ DDD : num [1:5602] 0 0 1.1 0.3 0 29.9 1.1 0.1 0 25.8 ...
# $ EEE:'data.frame':	5602 obs. of  2 variables:
#   ..$ Date: Date[1:5602], format: "1999-10-28" "1999-10-29" "1999-10-30" ...
# ..$ EEE : num [1:5602] 0 0 0 0 0 36.2 0 0 10.2 24.1 ... 
#' @references
#' Data source:
#' http://meteo.navarra.es/estaciones/mapadeestaciones.cfm
#' http://www4.gipuzkoa.net/oohh/web/esp/02.asp
#' @export
extractPeriod <- function(datalist,startDate = NULL,endDate = NULL, commonPeriod = F){
  message('dataset has to be generated by dput() and read by dget(), list based dataset,
          with first column to be the Date')
  
  if (!is.null(startDate)&!is.null(endDate)&commonPeriod == F){
    dataset <- lapply(datalist,extractPeriod_dataset,startDate=startDate,endDate=endDate)
  }else if (is.null(startDate)&is.null(endDate)&commonPeriod == T){
    
    Dates <- lapply(datalist,extractPeriod_getDate) 
    Dates <- do.call('rbind',Dates)
    
    startDate <- zoo::as.Date(max(Dates[,1]))
    endDate <- zoo::as.Date(min(Dates[,2]))
    
    dataset <- lapply(datalist,extractPeriod_dataset,startDate=startDate,endDate=endDate)
    
  }else{
    stop ('Enter startDate and endDate, set commonPeriod as False, or simply set commonPeriod as TRUE')
  }
  
  return(dataset)
}


#' Extract data from a dataframe with startDate and endDate
#' 
#' @param dataset A dataset with first column being a series of date or time.
#' @param startDate A date representing the start date.
#' @param endDate A date representing the end date.
#' @return The extracted dataframe between \code{startDate} and \code{endDate}.
extractPeriod_dataset <- function(dataset, startDate, endDate){
  
  dataset[,1] <- as.Date(dataset[,1])
  
  startIndex <- which(dataset[,1] == startDate)
  endIndex <- which(dataset[,1] == endDate)
  
  output <- dataset[startIndex:endIndex,]
  
  return (output)  
}

extractPeriod_getDate <- function(dataset){
  start <- as.Date(dataset[1,1])
  end <- as.Date(tail(dataset[,1],1))
  
  return (c(start,end))
}
